### PR TITLE
Attempting to add lat/lon to the data view.

### PR DESCRIPTION
**Pull request by hishma**
Just for shots and giggles I tried to see what adding the lat/lon the data view would look like. But no worky 😢.

Can you advise?

### CODE REVIEW

**Comment by Epho** [comment]
Unfortunately, to achieve a 2x grid for mobile, I had to set up very specific grid template areas. It's not ideal IMO to add/change grid areas when needed, but it's all I could come up with to achieve this result while also allowing for full landscape on larger screens. I can think on this further and revisit if you anticipate the need to add or remove data periodically. See my pr #6 for what is currently required

**Comment by Epho** [comment]
In fact, if you don't care for the data list to go full width on larger screens, I could simplify this greatly by adhering to the same 2x grid for all screens. This would be much more flexible, removing the need for defined grid areas.

**Comment by hishma** [comment]
Yeah I'm not sure. May have a need to add even more data at some point…

I'm also retaining the basic premise of one log entry == one post. Wondering if it might make sense to allow a post to have one or more log entry (each with its own data).

**Comment by Epho** [comment]
Ok, seems to me it should have the most flexibility, allowing for an undetermined amount of data entries. I will revisit the grid and make it more accommodating.

**Pull request closed without merging**
